# Generated by Django 5.0.7 on 2024-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperresult',
            name='practice_locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperresult',
            name='professional_corporation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperresult',
            name='registrant_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
