name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-2

    - name: Get EC2 public IP
      run: |
        echo "EC2_HOST=$(aws cloudformation describe-stacks --stack-name ExampleDeploymentCdkStack --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" --output text)" >> $GITHUB_ENV

    - name: Get RDS details
      run: |
        echo "DB_ENDPOINT=$(aws cloudformation describe-stacks --stack-name ExampleDeploymentCdkStack --query "Stacks[0].Outputs[?OutputKey=='DBEndpoint'].OutputValue" --output text)" >> $GITHUB_ENV
        echo "DB_PORT=$(aws cloudformation describe-stacks --stack-name ExampleDeploymentCdkStack --query "Stacks[0].Outputs[?OutputKey=='DBPort'].OutputValue" --output text)" >> $GITHUB_ENV
        echo "DB_NAME=$(aws cloudformation describe-stacks --stack-name ExampleDeploymentCdkStack --query "Stacks[0].Outputs[?OutputKey=='DBName'].OutputValue" --output text)" >> $GITHUB_ENV
        echo "DB_SECRET_NAME=$(aws cloudformation describe-stacks --stack-name ExampleDeploymentCdkStack --query "Stacks[0].Outputs[?OutputKey=='DBSecretName'].OutputValue" --output text)" >> $GITHUB_ENV

    - name: Get DB credentials
      run: |
        DB_CREDS=$(aws secretsmanager get-secret-value --secret-id ${{ env.DB_SECRET_NAME }} --query SecretString --output text)
        echo "DB_USERNAME=$(echo $DB_CREDS | jq -r .username)" >> $GITHUB_ENV
        echo "DB_PASSWORD=$(echo $DB_CREDS | jq -r .password)" >> $GITHUB_ENV

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      run: |
        scp -r ./* ec2-user@${{ env.EC2_HOST }}:/home/ec2-user/app
        ssh ec2-user@${{ env.EC2_HOST }} '
          set -e
          cd /home/ec2-user/app
          
          # Update Python to 3.8
          sudo amazon-linux-extras enable python3.8
          sudo yum install -y python3.8

          # Create and activate virtual environment using Python 3.8 explicitly
          /usr/bin/python3.8 -m venv venv
          source venv/bin/activate
          
          echo "Python version in virtual environment:"
          python --version

          # Install dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Create .env file
          echo "DJANGO_SECRET_KEY='"'"'$DJANGO_SECRET_KEY'"'"'" > .env
          echo "DEBUG=False" >> .env
          echo "ALLOWED_HOSTS=${{ env.EC2_HOST }},localhost,127.0.0.1" >> .env
          echo "DB_NAME='"'"'${{ env.DB_NAME }}'"'"'" >> .env
          echo "DB_USER='"'"'${{ env.DB_USERNAME }}'"'"'" >> .env
          echo "DB_PASSWORD='"'"'${{ env.DB_PASSWORD }}'"'"'" >> .env
          echo "DB_HOST='"'"'${{ env.DB_ENDPOINT }}'"'"'" >> .env
          echo "DB_PORT=${{ env.DB_PORT }}" >> .env
          echo "CELERY_BROKER_URL='"'"'$CELERY_BROKER_URL'"'"'" >> .env
          
          # Set PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:/home/ec2-user/app

          # Ensure the correct PostgreSQL client is being used
          export PATH=/usr/pgsql-14/bin:$PATH
          which psql
          psql --version

          # Create database if it doesn't exist
          PGPASSWORD=${{ env.DB_PASSWORD }} psql -h ${{ env.DB_ENDPOINT }} -U ${{ env.DB_USERNAME }} -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '${{ env.DB_NAME }}'" | grep -q 1 || PGPASSWORD=${{ env.DB_PASSWORD }} psql -h ${{ env.DB_ENDPOINT }} -U ${{ env.DB_USERNAME }} -d postgres -c "CREATE DATABASE ${{ env.DB_NAME }}"

          # Run Django commands
          cd api_project
          python manage.py collectstatic --noinput
          python manage.py migrate
          
          # Restart the uvicorn service
          sudo systemctl restart uvicorn.service
        '