name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Session Manager plugin
      run: |
        curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
        sudo dpkg -i session-manager-plugin.deb

    - name: Create systemd service file
      run: |
        echo '[Unit]
        Description=Django Scraper Gunicorn daemon
        After=network.target

        [Service]
        User=ec2-user
        Group=ec2-user
        WorkingDirectory=/home/ec2-user/django-scraper
        ExecStart=/usr/local/bin/gunicorn --workers 3 --bind unix:/home/ec2-user/django-scraper/django_scraper.sock django_scraper.wsgi:application

        [Install]
        WantedBy=multi-user.target' > django_scraper.service

        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=ExampleDeploymentCdkStack/DjangoScraperInstance" --query "Reservations[].Instances[].InstanceId" --output text)
        aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --parameters commands="sudo mv /home/ec2-user/django_scraper.service /etc/systemd/system/ && sudo systemctl daemon-reload"

    - name: Deploy to EC2
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=ExampleDeploymentCdkStack/DjangoScraperInstance" --query "Reservations[].Instances[].InstanceId" --output text)
        
        echo '#!/bin/bash
        # Ensure Git is configured
        git config --global user.email "deployment@example.com"
        git config --global user.name "Deployment Script"

        # Clone the repository if it doesnt exist, otherwise pull latest changes
        if [ ! -d "/home/ec2-user/django-scraper" ]; then
          git clone https://github.com/stemsrd/example-deployment.git /home/ec2-user/django-scraper
        else
          cd /home/ec2-user/django-scraper
          git pull origin main
        fi

        cd /home/ec2-user/django-scraper
        pip3 install -r requirements.txt
        python3 manage.py migrate
        python3 manage.py collectstatic --noinput
        
        # Nginx configuration
        echo "server {
            listen 80;
            server_name _;

            location = /favicon.ico { access_log off; log_not_found off; }
            location /static/ {
                root /home/ec2-user/django-scraper;
            }

            location / {
                include proxy_params;
                proxy_pass http://unix:/home/ec2-user/django-scraper/django_scraper.sock;
            }
        }" | sudo tee /etc/nginx/conf.d/django_scraper.conf > /dev/null
        
        sudo nginx -t && sudo systemctl restart nginx
        sudo systemctl restart django_scraper
        ' > deploy.sh
        
        chmod +x deploy.sh
        
        aws ssm start-session --target $INSTANCE_ID --document-name AWS-StartInteractiveCommand --parameters command="bash -c '$(cat deploy.sh)'"