name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key to the agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # Copy files to the EC2 instance
        scp -o StrictHostKeyChecking=no -r ./* ec2-user@${EC2_HOST}:/home/ec2-user/app

        # Run deployment commands
        ssh -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} '
          set -e
          mkdir /home/ec2-user/app
          cd /home/ec2-user/app
          
          echo "Current Python versions:"
          python --version
          python3 --version
          python3.8 --version
          
          # Create and activate virtual environment using Python 3.8 explicitly
          /usr/bin/python3.8 -m venv venv
          source venv/bin/activate
          
          echo "Python version in virtual environment:"
          python --version
          
          # Upgrade pip and install requirements
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Set the DJANGO_SETTINGS_MODULE environment variable
          export DJANGO_SETTINGS_MODULE=api_project.settings
          
          # Run Django commands
          cd api_project
          python manage.py collectstatic --noinput
          python manage.py migrate
          
          # Restart the uvicorn service
          sudo systemctl restart uvicorn.service
          
          echo "Deployment completed successfully"
        ' || { echo "Deployment failed"; exit 1; }