name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd api_project
        python manage.py test

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key to the agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ec2-user@${EC2_HOST}:/home/ec2-user/app
        ssh -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} '
          cd /home/ec2-user/app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py migrate
          sudo cp uvicorn.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable uvicorn
          sudo systemctl restart uvicorn
        '