name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key to the agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # Create app directory if it doesn't exist
        ssh -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} '
          if [ ! -d "/home/ec2-user/app" ]; then
            mkdir /home/ec2-user/app
          fi'

        # Copy files to the EC2 instance
        scp -o StrictHostKeyChecking=no -r ./* ec2-user@${EC2_HOST}:/home/ec2-user/app

        # Run deployment commands
        ssh -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} '
          set -e
          
          cd /home/ec2-user/app
          
          # Update Python to 3.8
          sudo amazon-linux-extras enable python3.8
          sudo yum install -y python3.8

          echo "Current Python versions:"
          python --version
          python3 --version
          python3.8 --version
          
          # Create and activate virtual environment using Python 3.8 explicitly
          /usr/bin/python3.8 -m venv venv
          source venv/bin/activate
          
          echo "Current Python and SQLite versions:"
          python --version
          python -c "import sqlite3; print(f\"SQLite version: {sqlite3.sqlite_version}\")"
          python -c "import django; print(f\"Django version: {django.__version__}\")"

          
          # Upgrade pip and install requirements
          pip install --upgrade pip
          pip install "urllib3<2.0"
          pip install -r requirements.txt
          
          # Set the DJANGO_SETTINGS_MODULE environment variable
          export DJANGO_SETTINGS_MODULE=api_project.settings

          # Create staticfiles directory
          mkdir -p api_project/staticfiles
          
          # Run Django commands
          cd api_project
          python manage.py collectstatic --noinput -v 2
          python manage.py migrate -v 2
          
          # Restart the uvicorn service
          sudo systemctl restart uvicorn.service
          
          echo "Deployment completed successfully"
        ' || { echo "Deployment failed"; exit 1; }